server:
  port: 7001
  servlet:
    context-path: /ordercenter

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.176:3306/springcloud_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456

